name: Maven CI run validation on PR
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - develop
jobs:
  verify:
    name: Runs validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v5

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Run maven verify
        run: mvn verify --file pom.xml